version: "3"
services:
  php:
    build: ./php
    volumes:
      - ./htdocs:/usr/share/nginx/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./htdocs:/usr/share/nginx/html
    restart: always
    ports: ["8090:80"]
    depends_on: ["php"]